---
Organizations:
        - &OrdererOrg
          Name: ordererOrg
          ID: ordererMSP
          MSPDir: ./certs/ordererorg/msp
          Policies:
                  Readers:
                          Type: Signature
                          Rule: "OR('ordererMSP.member')"
                  Writers:
                          Type: Signature
                          Rule: "OR('ordererMSP.member')"
                  Admins:
                          Type: Signature
                          Rule: "OR('ordererMSP.admin')"
          OrdererEndpoints:
                  - orderer:7050
        - &Ngp
          Name: ngpMSP
          ID: ngpMSP
          MSPDir: ./certs/peerngp/msp
          Policies:
                  Readers:
                          Type: Signature
                          Rule: "OR('ngpMSP.member')"
                  Writers:
                          Type: Signature
                          Rule: "OR('ngpMSP.admin','ngpMSP.client')"
                  Admins:
                          Type: Signature
                          Rule: "OR('ngpMSP.admin')"
                  Endorsement:
                          Type: Signature
                          Rule: "OR('ngpMSP.peer')"
          AnchorPeers:
                  - Host: peer-ngp
                    Port: 7051

        - &AlnWick
          Name: alnMSP
          ID: alnMSP
          MSPDir: ./certs/peeraln/msp
          Policies:
                  Readers:
                          Type: Signature
                          Rule: "OR('alnMSP.member')"
                  Writers:
                          Type: Signature
                          Rule: "OR('alnMSP.admin','alnMSP.client')"
                  Admins:
                          Type: Signature
                          Rule: "OR('alnMSP.admin')"
                  Endorsement:
                          Type: Signature
                          Rule: "OR('alnMSP.peer')"
          AnchorPeers:
                  - Host: peer-aln
                    Port: 7052
                    
        - &GAP
          Name: gapMSP
          ID: gapMSP
          MSPDir: ./certs/peergap/msp
          Policies:
                  Readers:
                          Type: Signature
                          Rule: "OR('gapMSP.member')"
                  Writers:
                          Type: Signature
                          Rule: "OR('gapMSP.admin','gapMSP.client')"
                  Admins:
                          Type: Signature
                          Rule: "OR('gapMSP.admin')"
                  Endorsement:
                          Type: Signature
                          Rule: "OR('gapMSP.peer')"
          AnchorPeers:
                  - Host: peer-gap
                    Port: 7053            

Capabilities:
        Channel: &ChannelCapabilities
                V2_0: true
        Orderer: &OrdererCapabilities
                V2_0: true
        Application: &ApplicationCapabilities
                V2_0: true

Application: &ApplicationDefaults
        Organizations:

        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "ANY Admins"
                LifecycleEndorsement:
                        Type: ImplicitMeta
                        Rule: "ANY Endorsement"
                Endorsement:
                        Type: ImplicitMeta
                        Rule: "ANY Endorsement"
        Capabilities:
                <<: *ApplicationCapabilities

Orderer: &OrdererDefaults
        OrdererType: solo
        Addresses:
                - orderer:7050
        BatchTimeout: 2s
        BatchSize:
                MaxMessageCount: 10
                AbsoluteMaxBytes: 99 MB
                PreferredMaxBytes: 512 KB
        Organizations:
                
        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "ANY Admins"
                BlockValidation:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"

Channel: &ChannelDefaults
        Policies:
                Readers:
                        Type: ImplicitMeta
                        Rule: "ANY Readers"
                Writers:
                        Type: ImplicitMeta
                        Rule: "ANY Writers"
                Admins:
                        Type: ImplicitMeta
                        Rule: "ANY Admins"
        Capabilities:
                <<: *ChannelCapabilities

Profiles:
        OrdererGenesis:
                <<: *ChannelDefaults
                Orderer:
                        <<: *OrdererDefaults
                        Organizations:
                                - *OrdererOrg 
                        Capabilities:
                                <<: *OrdererCapabilities
                Consortiums:
                        NgpConsortium:
                                Organizations:
                                        - *Ngp
                                        - *AlnWick
                                        - *GAP
        AlnWickChannel:
                Consortium: NgpConsortium
                <<: *ChannelDefaults
                Application:
                        <<: *ApplicationDefaults
                        Organizations:
                                - *AlnWick
                        Capabilities:
                                <<: *ApplicationCapabilities
        GAPChannel:
                Consortium: NgpConsortium
                <<: *ChannelDefaults
                Application:
                        <<: *ApplicationDefaults
                        Organizations:
                                - *GAP
                        Capabilities:
                                <<: *ApplicationCapabilities                        
