version: '2'

networks:
        ca:

services:
        ngp-ca:
                image: hyperledger/fabric-ca:1.4.8
                container_name: ngp-ca
                environment:
                        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
                        - FABRIC_CA_SERVER_CA_NAME=ngp-ca
                        - FABRIC_CA_SERVER_TLS_ENABLED=false
                        - FABRIC_CA_SERVER_PORT=7054
                        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
                ports:
                        - "7054:7054"
                command: sh -c 'fabric-ca-server start -d'
                volumes:
                        - ./ca/ngp-ca:/etc/hyperledger/fabric-ca-server
                networks:
                        - ca

        aln-ca:
                image: hyperledger/fabric-ca:1.4.8
                container_name: aln-ca
                environment:
                        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
                        - FABRIC_CA_SERVER_CA_NAME=aln-ca
                        - FABRIC_CA_SERVER_TLS_ENABLED=false
                        - FABRIC_CA_SERVER_PORT=7054
                        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
                ports:
                        - "7055:7054"
                command: sh -c 'fabric-ca-server start -d'
                volumes:
                        - ./ca/aln-ca:/etc/hyperledger/fabric-ca-server
                networks:
                        - ca

        gap-ca:
                image: hyperledger/fabric-ca:1.4.8
                container_name: gap-ca
                environment:
                        - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
                        - FABRIC_CA_SERVER_CA_NAME=gap-ca
                        - FABRIC_CA_SERVER_TLS_ENABLED=false
                        - FABRIC_CA_SERVER_PORT=7054
                        - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
                ports:
                        - "7056:7054"
                command: sh -c 'fabric-ca-server start -d'
                volumes:
                        - ./ca/gap-ca:/etc/hyperledger/fabric-ca-server
                networks:
                        - ca                

        ord-ca:
               image: hyperledger/fabric-ca:1.4.8
               container_name: ord-ca
               environment:
                       - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
                       - FABRIC_CA_SERVER_CA_NAME=ord-ca
                       - FABRIC_CA_SERVER_TLS_ENABLED=false
                       - FABRIC_CA_SERVER_PORT=7054
                       - FABRIC_CA_SERVER_CSR_HOSTS=0.0.0.0
               ports:
                       - "7057:7054"
               command: sh -c 'fabric-ca-server start -d'
               volumes:
                       - ./ca/ord-ca:/etc/hyperledger/fabric-ca-server
               networks:
                       - ca
